edit:
  objects: ["pickable things", "background"]
  operations: "extraction" 
  targets: "pickable things" # the target object should be chosen from the object list
  threshold: 0.24 # leave it empty if using argmax
